# Dependencies
markdown:     kramdown
highlighter:  rouge

# Exclude these
exclude:
- README
- CNAME

# Setup
title:            blowmage
tagline:          'A Mike Moore joint'
description:      'My name is Mike Moore. I like to hack with Ruby. You can <a href="http://humanecode.com/hire">hire me</a>.'
url:              http://blowmage.com/
